name: 0-first-workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_0_welcome:
    runs-on: ubuntu-latest
    steps:
      - name: step 0 Welcome to GitHub Actions
        run: echo "step 0 Welcome to GitHub Actions!"
      - name: step 1 touch file
        run: touch file.txt
      - name: step 2 echo file
        run: echo "This is a file" > file.txt
      - name: step 3 cat file
        run: cat file.txt
    
  job_1_ls:
    runs-on: ubuntu-latest
    steps:
      - name: step 0 LS
        run: ls -al

  job_2_ls_encadenado:
    runs-on: ubuntu-latest
    needs: job_0_welcome
    steps:
      - name: step 0 LS
        run: ls

  job_3_checkout_ls_file_encadenado:
    runs-on: ubuntu-latest
    needs: job_0_welcome
    steps:
      - name: step 0 Checkout
        uses: actions/checkout@v4.2.2
      - name: step 1 LS
        run: ls -al